ONCOLOGY_AS_STR = {"COMPREHENSIVE CANCER CENTERS OF NEVADA": "Rep21",
                   "BLUE RIDGE CANCER CARE": "Rep15",
                   "TEXAS ONCOLOGY PA": "Rep1",
                   "NEW YORK ONCOLOGY HEMATOLOGY": "Rep28",
                   "CANCER CENTERS OF NORTH CAROLINA": "Rep15",
                   "CANCER CARE CTR OF S TEXAS": "Rep1",
                   "ROCKY MOUNTAIN CANCER CTR": "Rep21",
                   "VIRGINIA CANCER SPECIALISTS PC": "Rep15",
                   "ARIZONA ONCOLOGY ASSOCIATES PC": "Rep18",
                   "MARYLAND ONCOLOGY HEMATOLOGY": "Rep13",
                   "VENANGO ONCOLOGY HEMATOLOGY ASSOCIATION": "Rep25",
                   "COMPASS ONCOLOGY THE NW CANCER SPEC": "Rep32",
                   "ARKANSAS ONCOLOGY ASSOCPA": "Rep12",
                   "CANCER CENTERS OF THE CAROLINAS": "Rep15",
                   "OCALA ONCOLOGY CENTER": "Rep5",
                   "CANCER CARE HEMATOLOGY SPEC CHICAGOLAND": "Rep7",
                   "GREENVILLE HOSPITAL SYSTEM": "Rep15",
                   "MISSOURI CANCER ASSOCIATES": "Rep19",
                   "REGIONAL CANCER CARE": "Rep15",
                   "VIRGINIA ONCOLOGY ASSOCIATES": "Rep25",
                   "MINNESOTA ONCOLOGY HEMATOLOGY ASSOCIATES": "Rep30",
                   "SOUTH FLORIDA ONCOLOGY AND HEMATOLOGY CO": "Rep5",
                   "OKLAHOMA MULTISPECIALTY GROUP": "Rep1",
                   "WILLAMETTE CANCER INSTITUTE": "Rep32",
                   "SHENANDOAH ONCOLOGY PC": "Rep15",
                   "THE HOPE CENTER FOR CANCER CARE": "Rep1",
                   "ILLINOIS CANCER SPCFOX VALLEY HEM ONC": "Rep7",
                   "ONCOLOGY RADIATION ASSOCIATES PA": "Rep5",
                   "FLORIDA CANCER AFFILIATES": "Rep5",
                   "ARIZONA STATE UROLOGICAL INSTITUTE": "Rep18",
                   "AFFILIATED ONCOLOGIST": "Rep7",
                   "SPECIALISTS HOSPITAL SHREVEPORT": "Rep10",
                   "COMPREHENSIVE RADIOLOGY": "Rep1",
                   "ARA IMAGING": "Rep1",
                   "AUSTIN RADIOLOGY ASSOC": "Rep1"}
