SELECT_AS_STR = {"SELECT - TULSA": "Rep1",
                 "SELECT HOUSTON HEIGHTS": "Rep1",
                 "SELECT MEDICAL CORPORATION": "Rep1",
                 "SELECT OK CITY EAST": "Rep1",
                 "SELECT SPECIAILTY HOSPITAL": "Rep1",
                 "SELECT SPECIALITY HOSP DALLAS": "Rep1",
                 "SELECT SPECIALITY HOSP. DALLAS": "Rep1",
                 "SELECT SPECIALTY HOSP-CONROE": "Rep1",
                 "SSH - OAKLAHOMA CITY WEST": "Rep1",
                 "SSH-OKLAHOMA CITY WEST": "Rep1",
                 "KESSLER EAST": "Rep23",
                 "KESSLER NORTH": "Rep23",
                 "KESSLER WELKIND": "Rep23",
                 "KESSLER WEST": "Rep23",
                 "SELECT SPEC HOSP- CAMP HILL": "Rep13",
                 "SELECT SPEC HOSP-WILMINGTON": "Rep13",
                 "SELECT SPEC. HOSP.- CAMP HILL": "Rep13",
                 "SELECT SPECIALTY HOSP-YORK": "Rep13",
                 "SELECT SPEC HOSP OF AKRON": "Rep25",
                 "SELECT SPEC HOSP OF BATTLE CK": "Rep3",
                 "SELECT SPEC HOSP OF WEST MICH": "Rep3",
                 "SELECT SPEC HOSP. OF BATTLE CK": "Rep3",
                 "SELECT SPEC HOSP.-PONTIAC": "Rep3",
                 "SELECT SPEC HOSPITAL-FLINT": "Rep3",
                 "SELECT SPEC HOSP-PONTIAC": "Rep3",
                 "SELECT SPEC HOSP-SAGINAW": "Rep3",
                 "SELECT SPEC HOSP-WYANDOTTE": "Rep3",
                 "SELECT SPEC OF CANTON": "Rep25",
                 "SELECT SPEC. HOSP. OF AKRON": "Rep25",
                 "SELECT SPEC. HOSPITAL-FLINT": "Rep3",
                 "SELECT SPECIALTY HOSP-NW DETRT": "Rep3",
                 "SELECT SPECIALTY HOSP-YOUNGSTO": "Rep3",
                 "SELECT SPECLTY HOSP-ANN ARBOR": "Rep3",
                 "SELECT SPECLTY HOSP-MACOMB CTY": "Rep3",
                 "SELECT SPEC HOSPITAL-TOPEKA": "Rep9",
                 "SELECT SPECIALTY HOSP-ST LOUIS": "Rep9",
                 "SELECT SPECIALTY HOSP-WEST MO": "Rep9",
                 "SELECT SPECIALTY-WICH-CHRISTI": "Rep9",
                 "SELECT SPECIALTY HOSP MIAMI": "Rep5",
                 "SELECT HOSPITAL-LEXINGTON": "Rep25",
                 "SELECT MED.OF CIN(GD.SAM.HSPT)": "Rep25",
                 "SELECT MEDOF CINGDSAMHSPT": "Rep25",
                 "SELECT SPC EAST=COLUMBUS SSH": "Rep25",
                 "SELECT SPC EASTCOLUMBUS SSH": "Rep25",
                 "SELECT SPC/COLUMBUS OSU": "Rep25",
                 "SELECT SPC/COLUMBUS RIVERSIDE": "Rep25",
                 "SELECT SPC/GRANT WEST": "Rep25",
                 "SELECT SPCCOLUMBUS OSU": "Rep25",
                 "SELECT SPCCOLUMBUS RIVERSIDE": "Rep25",
                 "SELECT SPCGRANT WEST": "Rep25",
                 "SELECT SPEC HOSP.-FT WAYNE": "Rep25",
                 "SELECT SPEC HOSP.-NW INDINANA": "Rep25",
                 "SELECT SPEC HOSP-FT WAYNE": "Rep25",
                 "SELECT SPEC HOSP-GREENSBURG": "Rep25",
                 "SELECT SPEC HOSP-JOHNSTOWN": "Rep25",
                 "SELECT SPEC HOSP-NW INDINANA": "Rep25",
                 "SELECT SPECIAL HOSP-EVANSVILL": "Rep25",
                 "SELECT SPECIAL. HOSP-EVANSVILL": "Rep25",
                 "SELECT SPECIALITY HOSP.PITTSBU": "Rep25",
                 "SELECT SPECIALITY HOSPITAL": "Rep25",
                 "SELECT SPECIALITY HOSPPITTSBU": "Rep25",
                 "SELECT SPECIALTIES-MT CARMEL": "Rep25",
                 "SELECT SPECIALTY - ERIE": "Rep25",
                 "SELECT SPECIALTY HOSP": "Rep25",
                 "SELECT SPECIALTY HOSP.": "Rep25",
                 "SELECT SPECIALTY HOSP-BEECH": "Rep25",
                 "SELECT SPECIALTY HOSP-CHARLEST": "Rep25",
                 "SELECT SPECIALTY HOSP-INDIANAP": "Rep25",
                 "SELECT SPECIALTY HOSP-DURHAM": "Rep15",
                 "SELECT SPEC HOSPITAL-DENVER": "Rep21",
                 "SELECT SPEC. HOSPITAL-DENVER S": "Rep21",
                 "SELECT SPECIALITY HOSPITAL- DENVER SOUTH": "Rep21",
                 "SPECIALITIY SELECT HOSPITAL DENVER": "Rep21",
                 "RUSH FOUNDATION HOSPITAL JIT": "Rep29",
                 "RUSH FOUNDATION HOSPITAL N JIT": "Rep29",
                 "SELECT AUGUSTA": "Rep29",
                 "SELECT MEMPHIS": "Rep29",
                 "SELECT SPECIALTY HOSP./B'HAM": "Rep29",
                 "SELECT SPECIALTY HOSP-ATLANTA": "Rep29",
                 "SELECT SPECIALTY HOSPBHAM": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-AUG": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-KNOX": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-KNOXVILLE": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-N KN": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-N KNOXVILLE": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-NASH": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-NASHVILLE": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-TRI": "Rep29",
                 "SELECT SPECIALTY HOSPITAL-TRI CITIES": "Rep29",
                 "BILOXI SPECIALTY HOSPITAL": "Rep12",
                 "SELECT FORT SMITH": "Rep12",
                 "SELECT LITTLE ROCK": "Rep12",
                 "SELECT MEDICAL CORP-OMAHA": "Rep34",
                 "SELECT SPEC HOSP- SIOUX FALLS": "Rep11",
                 "SELECT SPEC HOSP-MILWAUKEE": "Rep31",
                 "SSH - JEFFERSON PARISH": "Rep10",
                 "SELECT SPEC HOSP- KNOXVILLE UN OF TENN": "Rep29",
                 "SELECT SPECIALTY HOSPITAL - UPMC": "Rep25",
                 "SELECT SPECIALTY HOSPITAL - MCKEESPORT": "Rep25",
                 "SELECT SPEC HOSP-NW INDIANA": "Rep25",
                 "SELECT MEDICAL CORP": "Rep25",
                 "SELECT SPEC HOSPITAL-DENVER S": "Rep21",
                 "SELECT SPEC OF KANSAS CITY": "Rep9",
                 "SEMPERCARE HOSPITAL": "Rep29",
                 "SSH-PHOENIX DOWNTOWN": "Rep18",
                 "SELECT MED-PHOENIX": "Rep18",
                 "INOVA HEALTH SYSTEM": "Rep15",
                 "INOVA URGENT CARE WOODBRIDGE": "Rep15",
                 "URGENT MEDICAL CARE OF VIENNA": "Rep15",
                 "INOVA EMERGENCY CARE CENTER - RESTON": "Rep15",
                 "INOVA HEALTH CARE": "Rep15",
                 "INOVA HEALTH CARE SERVICES": "Rep15",
                 "INOVA OB CLINIC": "Rep15",
                 "INOVA OUTPATIENT NEUROLOGY": "Rep15",
                 "INOVA URGENT CARE": "Rep15",
                 "CONCENTRA HEALTH SERVICES INC": "Rep25",
                 }
